name: wp-plugin-testing-environment
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./.db_container_volume:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
    
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./.wp_container_volume:/var/www/html
      - ../.:/var/www/html/wp-content/plugins/${PLUGIN_SLUG}
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - ./.wp_container_volume:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf